Hotfix/parsing values
casper-ecosystem/casper-js-sdk pull request #123
Opened 2021-11-14 20:38 UTC by hoffmannjan

2021-11-14 23:29 UTC, KillianH commented
Hey,

here's my result with the testnet : 
Deploys KO :
```
aaa73fd21be9b7f19fc3cf5ced3798ce4d88a430f90ba006827e1979fac870ff
0ec1bb3d3ec452869ea0feb0c05a521c9870994122ddd4ade8cd86e75e064835
ce6bfc9a7d7b20c6ee774fbba73d77f996ffbdb0a5d814aa7e8248f9eda92f3d
cbae817bb86a817017853ed9698a3b53b8f1151de823c4028e1072f66a969c68
5d85732f56ecc643c2e1d27eacccf4d168da9d5aaa55dd71adcfd977ade3c4ba
0deebaa3044edda5c976de0e3f407397b136fa994831768ed6979d63f154adca
18d2371f2141534a7e8b4cafac01aa9e6b921974264dc5490206d46602f4a176
193a10ab287004e1d02c35c8c3d1375935e0cdee571b8bc0e72146e1884a8428
e81ca82022a14989ad5c238f1e07decb663d494b0e0637813b3c7d60697ebca4
60ca8b422032fcadabed38a108088316212f1fb9d32bc6ae55ccdbb5781cfb00
6d302c9d7c2db5f59d97ce70a86de56b18aac67d0c2f1002277e9d294db73194
1e32504f887df2e33db07cd9b48567290614c943f3518c06b7787d469b0b726b
125e913c232013787e396523ff6dc7e90cbbde1c7217752063719f48abc45003
7ce7d518a56221a025e8bde3d165183bac001af8f6fae1464c17bf0a2f04f22b
5c43215bae1f78bd04dd1b1e9b6a56f02b1807031dac3f2f9771465adedf8e7e
9db79460e31a665174193cde565fd8bf101a70e94b268dc62cd4295d983ee87d
82c8257f4caddf34e8efe7b60fc3ce6731a9e488669d63b6df0034b5593d4d34
e7f4a859f984237fed9a97382d4ec3e52c73b6f17ab96b18257994e425297ba2
aac1b785bae88ed4367ef9b4021293ffee00e09506f56cecf6b67f8c2ce01551
3b31d8ef5d7333cfcbf4cb54faef5d5b971a5d3a652ae0a13457289e53920ef8
90772ae212402838d0ab9ff3c323157619fc57eb32003160f52608647f234d4a
e3214991abe2cfe4f7093b84c60686ae9806dcc13551b55e38660e969bfaacff
228c4fe9051598942f9113f330b060fd21152ae5a4ce2975ebcd6776d6967b1b
fe83d12e0d3b945745a1d94544bcd71f551af67bbc4c1d733ca750ea8c8306f9
f4be922dd9effd15e3706b4058395e451553863d1460b0a455f96b767608416a
24cc3298694f3c345fc95d587207742d669928934ba989fa15660e41f31cd390
99ec1652af0220656f093f5d6796ec578011284a53ce1927fd20abf37e8dd4c8
0e2f61aa54d9e9e6fc9b86269ebc3baf5a6534bab26cc028dea7133664884579
4cc2c31e422ce617765ba003dceeefbef64669bea5f42110476315a532f0f8fd
ce46b1234ac79c7b0b4901b2df0dd612b34a7205c0980a8cb4b941d3ceb2c4b2
9bcf8c15f111be6adb7c5c7601e47de6ec0ecfa226e471ee8d5728cc9e1fb1dd
13e18a7f6798e43291c0abf0dd8e8b027fd0d8428a62ec5455682aab7a558d20
23cfd1c93c83c4056a3f14846270de7fe7131a6b2639873472d33403038651fb
b691e73b537a9431c3416c99bd615d25a285e5e3b4cc226a82426f89ae23c112
049f058cf0bba42788ccac4f25633204beecde1590a0ee92371fffd2d930ec6f
bfd2542e3ba4bf6bcf28ef5965233c34be0cc32c25191de782ef76f5a33460d0
754f0ecf726d66032dfb3ee1ad181585fb109f976dbc22fa7759173193119516
6d7dbd3f2c72a1fc3a2effa18be9e2b7cf6a4574bdb91bbe171c56dd1285321a
e8e5b1c7f395a03820fa26200a26f3f10f2fa6a009508bd5688c374b4fb5fb7c
443fc44bafb3ab767f3398bd2abb7599e15b4e6bae92a2a1c69363f5fc5c1edc
e6a035f2c8335441a5a603b46c3a73bdd118bdb6e70ba7a6f2b5af7c12305be2
3aeb2ad2b209291fa3d15166cdd6768cfeae91414533a39961b3c69dd83bf8f7
4d455de4a36ce0fde47b6a84e59652e4ddd103f59e91fb694d04b308912af979
4017c4c3ba47d5d26934247ecdf4c41d06005f4c7d5e1723317fd5877449e8b2
d45d3ca68bee50dcf5b139a723d407b4b6a237c3081b1bffed15835206eb61e4
1eea0ed5ab843af2c5cb189bb13b3094d07d9389e2e04417e26c8c2a53004a6b
c7509dec5f8fbfa6a2753c2f5980691ba8eba5dc187f38dea04629d61d2473a7
5899add0de77771afebfde21ee47ea1963bc3b854af444bcc1d6c95840f513e4
e2bed34a3b8ea4af52c39f0baef6492ae05cd59da3883328e34eb8b943b15425
308c11f2d81712be993b7913b633798260d84d017328f43b29da8052f01a2591
e67f0d6a221a2228b1dff42af4aeb6082cc1506b4f751317add086be5c841c36
fb60fd74f35738d161a189452258388b994bfa25a436f04d23d1621e47d9962f
1db9100a28d6f21f55d175d3e9e6d2d8a16ec3394e6660c8ac6c5106aa4bbab6
cab7a742e660cb84fb36a0a7ee432c397dd9f56f1f27f38d5994fb14bb973ee1
2d8c8a81fc2a65eadbe47f3a79105321db496cfcc05a2babf7e35550f9d809e0
cbed94db7c5a7e4a544a11d85f4c46e393f7b4fc31af586ea0251b5769a8216e
0b58224988d377e412e7d7e108c547efd8ea3984f85e0b1e516f26c9ead09fd6
0fc55ccbdb0c9a145e0517c08c4068b43a942e0147f6393d89a4690cb788087c
ee6c7b76f2d75ae364413509327c2b38aa9eb0dc85cdaab3b99902238f336a37
d057d876113c37160bd297e4792a002c8e0d477dc62c8b36f3cfc637f4ad596c
244d731044e1b7059507b9191a041844e93c8afa8789f03b5c5632ea85a7e286
1b53b81a7df5aea7d899663787ca4ae23482997612ba5312cb2521602b5b7f66
2d025da629812d3c2e84d11c21ba7e6dd9ac13e94b4ba4c79a7b3c86c1b381a3
34f48231b501c112edfc16f6a04fe26bda2fcea129d078f8f41cabedebbb5d39
e5aac80274490685a015e954b8e761b3996358967b3896641b675e9f6db68703
d69b919b2a1056b3fa59c88863a11c989496c40e2ee1e9f4d5fe4b7f08d7fcc4
e685b1996e93a2d099f14bc94fb696f29a3ea7be232c5db3d035098c677ad0f6
3f4df2f68a94a7340a9a010b26a9a3425b685dad9cd17ab359cbe66687d2becc
efe6bef366b4bc9ead3b7e04be6f8eac8ed42da8a55dc4eda922f7927bd3dfb3
2c36fe6ca5c7c8da052d22b5c08f5eeecd8afc00ce4aaea0f330a554b953804d
bd2f9540c284d315e940b9febdc7355890a599e60f2f64b125452398a9f5cf5a
1c09636fc22a4c54598b370db181c16f26c0e4a735b587710820bcd6cc09a456
5380b160ad62b3cabc83a62eaec9ac1cfdddfb16753da963967486d059c42c45
```
Transfers KO :
```
482a4704c4835205e70bcf70379cb5250a063e35b0d73f7cfb54263fb58cb478
0cace0cdd32e32f2ae9590ddcfcd3017d42bf08a426f29f60cddf730e74b2f8e
aa83cd17bd3a2147b40737b58d35fc102f39125c1d6c756e8e58eed1e7229efd
```

You can test those with the same code in the issue #116

2021-11-18 05:30 UTC, KillianH commented
```
Failed to retrieve transfer e14d29611e67dfbae4ce05579b5983047144bf77ca351a654c9831b89c56636e                                                                                                                                                                                                                               
 Error: Tried to unwrap Error: Error: Invalid deploy: bodyHash missmatch. Expected: 51,123,113,32,158,89,66,222,223,238,180,56,54,77,245,218,240,248,38,191,211,142,123,240,211,227,108,57,96,140,129,233,                                                                                                                  
                   got: 81,64,119,139,86,217,155,201,39,236,254,189,30,12,12,4,71,131,167,81,23,122,124,101,81,236,188,201,215,139,16,121.                                                                                                                                                                                  
     at Object.deployFromJson (/snapshot/node_modules/casper-js-sdk/dist/lib.node.js:1:81360)                                                                                                                                                                                                                               
     at /snapshot/node_modules/casper-js-sdk/dist/lib.node.js:1:58603                                                                                                                                                                                                                                                       
     at runMicrotasks (<anonymous>)                                                                                                                                                                                                                                                                                         
     at processTicksAndRejections (node:internal/process/task_queues:96:5)                                                                                                                                                                                                                                                  
     at ErrImpl.unwrap (/snapshot/node_modules/ts-results/result.js:53:19)                                                                                                                                                                                                                                                  
     at /snapshot/node_modules/casper-js-sdk/dist/lib.node.js:1:58621                                                                                                                                                                                                                                                       
     at runMicrotasks (<anonymous>)                                                                                                                                                                                                                                                                                         
     at processTicksAndRejections (node:internal/process/task_queues:96:5)                                                                                                                                                                                                                                                  
 Failed to retrieve transfer d388e4e79d1e29bf7c774d79f2bb6fd8c94cb208ddb8cd6e48612107236840bd                                                                                                                                                                                                                               
 Error: Tried to unwrap Error: Error: Invalid deploy: bodyHash missmatch. Expected: 11,192,21,161,48,90,22,10,87,193,226,186,252,139,244,245,89,94,191,184,210,108,214,246,13,115,159,248,117,6,201,146,                                                                                                                    
                   got: 113,42,0,77,113,88,168,98,255,223,164,162,77,15,242,86,197,185,185,187,240,116,183,44,71,164,233,104,22,151,69,96.                                                                                                                                                                                  
     at Object.deployFromJson (/snapshot/node_modules/casper-js-sdk/dist/lib.node.js:1:81360)                                                                                                                                                                                                                               
     at /snapshot/node_modules/casper-js-sdk/dist/lib.node.js:1:58603                                                                                                                                                                                                                                                       
     at runMicrotasks (<anonymous>)                                                                                                                                                                                                                                                                                         
     at processTicksAndRejections (node:internal/process/task_queues:96:5)                                                                                                                                                                                                                                                  
     at ErrImpl.unwrap (/snapshot/node_modules/ts-results/result.js:53:19)                                                                                                                                                                                                                                                  
     at /snapshot/node_modules/casper-js-sdk/dist/lib.node.js:1:58621                                                                                                                                                                                                                                                       
     at runMicrotasks (<anonymous>)                                                                                                                                                                                                                                                                                         
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

2021-12-17 17:36 UTC, KillianH commented
Hey @hoffmannjan any update on this ? :)

2021-12-17 18:08 UTC, George-cl commented
> Hey @hoffmannjan any update on this ? :)

This is kind of on me - need to finish my review of the changes - hoping to finish tonight @hoffmannjan

2021-12-17 18:19 UTC, KillianH commented
> > Hey @hoffmannjan any update on this ? :)
> 
> This is kind of on me - need to finish my review of the changes - hoping to finish tonight @hoffmannjan 

No problem. Does the deploy that I provided aren't included in the fix ?

2021-12-18 20:49 UTC, George-cl requested changes
Changes look good to me, I've marked two bits of commented code that can probably be removed now. I think @KillianH wants clarification on if it fully resolves all the examples he shared.

2021-12-18 20:49 UTC, George-cl commented on src/lib/CLValue/Key.ts
> +  // ACCOUNT_HASH_LENGTH,
Can this be removed if it's not being used?

2021-12-18 20:49 UTC, George-cl commented on src/lib/CLValue/Key.test.ts
> +
Can this be removed if it's not being used?
Looks like its been superseded by the test above

2021-12-20 12:29 UTC, hoffmannjan commented
> > > Hey @hoffmannjan any update on this ? :)
> > 
> > 
> > This is kind of on me - need to finish my review of the changes - hoping to finish tonight @hoffmannjan
> 
> No problem. Does the deploy that I provided aren't included in the fix ?

Hi @KillianH, I think we need to split this into few different issues, as most of the failing deploys shows problem with different `CLType`, also it involves some changes how `RunTimeArgs` works so this is pretty big change to do. 
I think I will have time to tackle it after new year, but will try to create issues and tag you (so you will be notified about changes) this week :).

2022-01-08 00:04 UTC, George-cl approved these changes

2022-01-10 12:54 UTC, merged